language: python
python:
  - "2.7"

branches:
  only:
    - master

env:
  - TOXENV=py27

before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip scipy numpy pandas scikit-learn joblib nipype h5py seaborn
  - pip install nibabel nilearn pytest pytest-cov coveralls pytest-pep8
  - sudo apt-get install -y curl
  - curl -sSL http://neuro.debian.net/lists/trusty.us-ca.full >> /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
  - sudo apt-get update
  - sudo apt-get install -y fsl-core
  - export FSLOUTPUTTYPE=NIFTI_GZ
install:
  # Replace dep1 dep2 ... with your dependencies
  - python setup.py install

script:
  - py.test -v --cov skbold --cov-report term-missing skbold

after_success:
    - coveralls
